name: GitHub Pages Build

on:
  push:
    branches:
      - main # Set a branch to deploy

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          lfs: true # Fetch large files

      - name: Turn off LFS
        run: >-
          git lfs uninstall;
          rm -Rf .git;
          rm .gitattributes;

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest

      - name: Compile static files
        run: |
          npm i
          npm run build

      - name: Get git log
        run: |
          git log --pretty=format:"@@@%h>%ad>%s" > public/log.txt

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp-europe.nekoweb.org
          port: 30000
          username: iddeko
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./iddeko.nekoweb.org/
